paths:
  # --- General Paths ---
  log_dir: ".slurmlogs"
  phenotypes: "data/processed/phenotypes"
  output_dir: "data/processed"
  results_dir: "results"
  scripts:
    ropscan: "scripts/01_ropScan.R"
    perm_chunk: "scripts/02a_runPermChunk.R"
    perm_agg: "scripts/02b_aggregatePerms.R"
    detect_loci: "scripts/03_detectSigLoci.R"

params:
  # --- Workflow Parameters ---
  # Parameters that are the same for both modes
  common:
    norm: ["boxcox"]
    agg: ["individual"]

  # Parameters specific to 'test' mode
  test:
    qtl_trait: ["BW.day.0", "BW.day.21"]
    drug: ["Ctrl"]
    num_perms: 20
    chunk_size: 5

  # Parameters specific to 'full' mode
  full:
      qtl_trait: ["BW.day.0", "TH", "LV", "RV", "LA", "RA",  "Wall.Thicknessd.21", "Delta.Wall.Thickness.d", "Percent.Fibrosis", "CSA"]
      drug: ["Ctrl", "Iso"]
      num_perms: 100
      chunk_size: 5

resources:
  # --- Cluster Resources ---
  run_ropscan_and_gen_perms:
    test: { mem_mb: 400, time: "00:04:00" }
    full: { mem_mb: 4000, time: "00:55:00" }
  run_permutation_chunk:
    test: { mem_mb: 500, time: "00:08:00" }
    full: { mem_mb: 4000, time: "02:00:00" }
  aggregate_permutations:
    test: { mem_mb: 500, time: "00:03:00" }
    full: { mem_mb: 6000, time: "00:30:00" }
  detect_significant_loci:
    test: { mem_mb: 1000, time: "00:05:00" }
    full: { mem_mb: 8000, time: "00:20:00" }